version: 2.1

jobs:
  node_latest: &test
    docker:
      - image: node:latest
    working_directory: ~/sdu
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: npm test
  node_8:
    <<: *test
    docker:
      - image: node:8
  node_10:
    <<: *test
    docker:
      - image: node:10
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  tests:
    jobs:
      - node_latest
      - node_8
      - node_10
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
